server:
  port: 8888
  servlet:
    context-path: /crm

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: zwt123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    date-format: yyyy-MM-dd